### ISSUE TITLE
Port PowerPing to other platforms

### ISSUE THREAD

**Issue by Killeroo** [Killeroo/PowerPing#21]
- [x] Restructure project for dotnet and .net4.5 builds
- [x] Create Bash build script for building project with .netcore
- [x] Create Bash build script for building project with mono
- [x] Batch script for building standard windows binary
- [x] Travis CI yml script for .netcore and mono (couple of versions of each) (could use previous build script)
- [ ] Add platform/build info to version text (also remove build date)
- [x] Make sure file versions persist with .net core builds
- [ ] Installers for each build platform

**Comment by Killeroo** [comment]
Look at getting verified publisher status:
https://stackoverflow.com/a/6869156

**Comment by Killeroo** [comment]
https://stackoverflow.com/a/20383002

**Comment by Killeroo** [comment]
Read me syntax:

# Platform Support

- Amazon Linux
- Debian 7/8/9
- Fedora
- Ubuntu 14.04/16.04
- CentOS 7

**Comment by Killeroo** [comment]
# TODO List
- [ ] Bash build script(s) for building project with mono and .netcore
- [ ] Travis CI yml script for .netcore and mono (couple of versions of each) (could use previous build script)
- [ ] Batch script for building standard windows binary

**Comment by Killeroo** [comment]
dotnet commands
- dotnet restore
- dotnet build
- dotnet publish -c Release -r win10-x64 

Useful links
[Configuring csproj to build for other platforms ('Self-contained deployment without third-party')](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli)
[More csproj build config](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-vs)
[List of build targets](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)

**Comment by Killeroo** [comment]
## Packaging software
[Creating software package for the mac](https://technet.microsoft.com/en-gb/library/jj687950.aspx)

**Comment by Killeroo** [comment]
PowerPing has included scripts to allow it to build cross platform for linux, mac and windows using dotnetcore since (https://github.com/Killeroo/PowerPing/commit/f0b97c60e57522a9defb202f6e61850ecf66981c). 

However issues with the portability of the application (requiring installation of netcore) and general problems with things such as console formatting on other platforms (see https://github.com/Killeroo/PowerPing/issues/60 https://github.com/Killeroo/PowerPing/issues/61 https://github.com/Killeroo/PowerPing/issues/63 https://github.com/Killeroo/PowerPing/issues/64) have caused serious stability and inconsistency issues with PowerPing using dotnetcore.

Options like mono could be explored further and more attention to fixing these aforementioned netocore bugs could be followed up. But the amount of libraries and overhead required to run dotnetcore on other systems and the inability to create a truly portable application on these platforms has meant that focus has moved away from perfecting PowerPing for cross platform.

I know that PowerPing still requires a recent .Net framework (4.5) to run on modern windows machine, but the main aims of PowerPing was to create a small, lightweight and ideally single file application that could perform ping operations on _most_ versions of windows. With .NET framework existing on most versions of windows nowadays (Albiet with .NET framework no longer the core framework that Microsoft focuses on) PowerPing can achieve this goal. But building PowerPing on dotnetcore does not achieve any of these aims.

So for the foreseeable future, the main focus of PowerPing will be providing a more stable, fast and feature rich application for Windows, the cross platform issues mentioned will remain open as they are linked to problems that exist on Windows.  Maybe some day I'll properly revisit to cross platform implementation, I certainly won't forget about it.
